### ISSUE TITLE
Remove appServerRelation

### ISSUE THREAD

**Issue by yvespp** [a-gogo/agogo#20]
The appServerRelation feature is not used and should be removed from the GUI, DB and Java Code.

**Comment by phil-pona** [comment]
removed GUI Parts and Business on Branch https://github.com/a-gogo/agogo/tree/feature_remove_appserver_relations

TODO: Entities and Database Changes

**Comment by phil-pona** [comment]
removed Entities

TODO: create Liquibase Script for 
- TAMW_APPSERVERRELATION
- TAMW_APPSERVERRELATION_AUD
- TAMW_APPSERVERRELHIERARCHY
- TAMW_APPSERVERRELHIERARCHY_AUD

**Comment by yvespp** [comment]
Fixed in #29
