### ISSUE TITLE
Abschluss-Mail mit den Angaben zu Artefakt und Version

### ISSUE THREAD

**Issue by yvespp** [a-gogo/agogo#30]
Danke der Option die beim "confirm" eines Deployments aufpoppt, können wir den Abschluss eines Deployments automatisch mit einem Mail bestätigt lassen. Einen Teil des Mails können wir dann übertragen, falls das Deployment in Zusammenhang mit einem Defect steht.. Im Mail wird der Service und die Umgebung angezeigt, jedoch fehlt die Info zum Artefakt und Version. Diese Werte sollen auch gleich im Mail mitgeliefert werden. 

Es soll wie folgt aussehen:
AMW-Deployment: 123456 (vvn_praemienrechner on V)
ch_mobi_vvn_praemienrechner_jeeservice 2.0.0-27
ch_mobi_vvn_praemienrechner_rwc 2.0.0-82
… etc. …

**Comment by phil-pona** [comment]
im Branch feature_additional_mail_info gestartet

**Comment by yvespp** [comment]
Fixed in #31
